# OrangeHRM Configuration File
# Browser Configuration
browser=edge
# chrome, firefox, edge
# Note: Execution Mode is HEADED (Browser window will be VISIBLE)

# Application URL
url=https://opensource-demo.orangehrmlive.com/web/index.php/auth/login

# WebDriver Wait Timeout (in seconds)
wait.timeout=10

# Implicit Wait (in seconds)
#implicit.wait=5

# Page Load Timeout (in seconds)
page.load.timeout=15

